version: "3.6"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 3001:3001
    links:
      - postgres
      - postgres:pg.local
    depends_on:
      - postgres
  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    ports:
      - 3000:3000
